name: Run Vale Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install docutils (rst2html)
        run: |
          pip install docutils

      - name: Install Vale
        run: |
          go install github.com/errata-ai/vale@latest

      - name: Get vale version
        run: |
          vale --version

      - name: Run tests
        run: |
          make test
