name: Run Vale Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Vale
        run: |
          go install github.com/errata-ai/vale/cmd/vale@latest

      - name: Run Vale
        run: |
          vale --version
          vale
